#!/usr/bin/env python3
"""Fixed country mapping based on actual names"""

ENHANCED_COUNTRIES = {
    'Argentina': {
        'name': 'Argentina',
        'faction': 'SWING',
        'alliance': 'none',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.5,
        'description': 'Swing state, non-nuclear',
    },
    'India': {
        'name': 'India',
        'faction': 'SWING',
        'alliance': 'QUAD',
        'nuclear_weapons': 164,
        'nuclear_status': 'confirmed',
        'morale': 0.7,
        'description': 'Swing state, nuclear power',
        'capital': [77.2090, 28.6139]  # New Delhi
    },
    'China': {
        'name': 'China',
        'faction': 'CHINA_BLOC',
        'alliance': 'SCO',
        'nuclear_weapons': 410,
        'nuclear_status': 'confirmed',
        'morale': 0.8,
        'description': 'Rising superpower, nuclear state',
        'capital': [116.4074, 39.9042]  # Beijing
    },
    'Israel': {
        'name': 'Israel',
        'faction': 'SWING',
        'alliance': 'none',
        'nuclear_weapons': 90,
        'nuclear_status': 'estimated',
        'morale': 0.8,
        'description': 'Swing state, nuclear power (estimated)',
        'capital': [34.7818, 31.7683]  # Jerusalem
    },
    'France': {
        'name': 'France',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 290,
        'nuclear_status': 'confirmed',
        'morale': 0.7,
        'description': 'NATO member, nuclear power',
        'capital': [2.3522, 48.8566]  # Paris
    },
    'North Korea': {
        'name': 'North Korea',
        'faction': 'CHINA_BLOC',
        'alliance': 'none',
        'nuclear_weapons': 30,
        'nuclear_status': 'estimated',
        'morale': 0.7,
        'description': 'China ally, nuclear power (estimated)',
        'capital': [125.7625, 39.0392]  # Pyongyang
    },
    'Ukraine': {
        'name': 'Ukraine',
        'faction': 'NATO_ALIGNED',
        'alliance': 'NATO_PARTNER',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.9,
        'description': 'NATO partner, seeking membership, non-nuclear',
    },
    'Belarus': {
        'name': 'Belarus',
        'faction': 'RUSSIA_BLOC',
        'alliance': 'CSTO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'CSTO member, non-nuclear',
    },
    'South Africa': {
        'name': 'South Africa',
        'faction': 'SWING',
        'alliance': 'BRICS',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.5,
        'description': 'Swing state, non-nuclear',
    },
    'Kazakhstan': {
        'name': 'Kazakhstan',
        'faction': 'RUSSIA_BLOC',
        'alliance': 'CSTO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.5,
        'description': 'CSTO member, non-nuclear',
    },
    'Brazil': {
        'name': 'Brazil',
        'faction': 'SWING',
        'alliance': 'BRICS',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'Swing state, non-nuclear',
    },
    'Russia': {
        'name': 'Russia',
        'faction': 'RUSSIA_BLOC',
        'alliance': 'CSTO',
        'nuclear_weapons': 5977,
        'nuclear_status': 'confirmed',
        'morale': 0.7,
        'description': 'Nuclear superpower, CSTO leader',
        'capital': [37.6173, 55.7558]  # Moscow
    },
    'Germany': {
        'name': 'Germany',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.65,
        'description': 'NATO member, non-nuclear',
    },
    'Turkey': {
        'name': 'Turkey',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'Poland': {
        'name': 'Poland',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.8,
        'description': 'NATO member, non-nuclear',
    },
    'Ireland': {
        'name': 'Ireland',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO member, non-nuclear',
    },
    'United Kingdom': {
        'name': 'United Kingdom',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 225,
        'nuclear_status': 'confirmed',
        'morale': 0.75,
        'description': 'NATO member, nuclear power',
        'capital': [-0.1276, 51.5074]  # London
    },
    'Italy': {
        'name': 'Italy',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'Iran': {
        'name': 'Iran',
        'faction': 'CHINA_BLOC',
        'alliance': 'SCO',
        'nuclear_weapons': 0,
        'nuclear_status': 'suspected',
        'morale': 0.6,
        'description': 'China ally, suspected nuclear program',
        'capital': [51.3890, 35.6892]  # Tehran
    },
    'Saudi Arabia': {
        'name': 'Saudi Arabia',
        'faction': 'SWING',
        'alliance': 'none',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.5,
        'description': 'Swing state, non-nuclear',
    },
    'Pakistan': {
        'name': 'Pakistan',
        'faction': 'SWING',
        'alliance': 'none',
        'nuclear_weapons': 170,
        'nuclear_status': 'confirmed',
        'morale': 0.6,
        'description': 'Swing state, nuclear power',
        'capital': [73.0479, 33.6844]  # Islamabad
    },
    'United States of America': {
        'name': 'United States',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 5244,
        'nuclear_status': 'confirmed',
        'morale': 0.8,
        'description': 'NATO leader, nuclear superpower',
        'capital': [-77.0369, 38.9072]  # Washington DC
    },
    'Canada': {
        'name': 'Canada',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO member, non-nuclear',
    },
    'Mexico': {
        'name': 'Mexico',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'US ally, non-nuclear',
    },
    'Egypt': {
        'name': 'Egypt',
        'faction': 'SWING',
        'alliance': 'none',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.5,
        'description': 'Swing state, non-nuclear',
    },
    'Australia': {
        'name': 'Australia',
        'faction': 'NATO_ALIGNED',
        'alliance': 'QUAD',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'US ally, non-nuclear',
    },
    'Japan': {
        'name': 'Japan',
        'faction': 'NATO_ALIGNED',
        'alliance': 'QUAD',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'US ally, non-nuclear',
    },
    'Spain': {
        'name': 'Spain',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'Romania': {
        'name': 'Romania',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'South Korea': {
        'name': 'South Korea',
        'faction': 'NATO_ALIGNED',
        'alliance': 'US_ALLY',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'US ally, non-nuclear',
    },
    'New Zealand': {
        'name': 'New Zealand',
        'faction': 'NATO_ALIGNED',
        'alliance': 'US_ALLY',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'US ally, non-nuclear',
    },
    'Sweden': {
        'name': 'Sweden',
        'faction': 'NATO_ALIGNED',
        'alliance': 'NATO_PARTNER',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO partner, non-nuclear',
    },
    'Finland': {
        'name': 'Finland',
        'faction': 'NATO_ALIGNED',
        'alliance': 'NATO_PARTNER',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO partner, non-nuclear',
    },
    'Switzerland': {
        'name': 'Switzerland',
        'faction': 'NATO_ALIGNED',
        'alliance': 'NATO_PARTNER',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO partner, neutral but aligned',
    },
    'Austria': {
        'name': 'Austria',
        'faction': 'NATO_ALIGNED',
        'alliance': 'NATO_PARTNER',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO partner, EU member',
    },
    'Georgia': {
        'name': 'Georgia',
        'faction': 'NATO_ALIGNED',
        'alliance': 'NATO_PARTNER',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO partner, seeking membership',
    },
    'Moldova': {
        'name': 'Moldova',
        'faction': 'NATO_ALIGNED',
        'alliance': 'NATO_PARTNER',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO partner, EU candidate',
    },
    'Netherlands': {
        'name': 'Netherlands',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO member, non-nuclear',
    },
    'Belgium': {
        'name': 'Belgium',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO member, non-nuclear',
    },
    'Denmark': {
        'name': 'Denmark',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO member, non-nuclear',
    },
    'Norway': {
        'name': 'Norway',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO member, non-nuclear',
    },
    'Portugal': {
        'name': 'Portugal',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'Greece': {
        'name': 'Greece',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'Czech Republic': {
        'name': 'Czech Republic',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO member, non-nuclear',
    },
    'Slovakia': {
        'name': 'Slovakia',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO member, non-nuclear',
    },
    'Hungary': {
        'name': 'Hungary',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'Bulgaria': {
        'name': 'Bulgaria',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'Croatia': {
        'name': 'Croatia',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'Slovenia': {
        'name': 'Slovenia',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'Estonia': {
        'name': 'Estonia',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO member, non-nuclear',
    },
    'Latvia': {
        'name': 'Latvia',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO member, non-nuclear',
    },
    'Lithuania': {
        'name': 'Lithuania',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.7,
        'description': 'NATO member, non-nuclear',
    },
    'Montenegro': {
        'name': 'Montenegro',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'Albania': {
        'name': 'Albania',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'North Macedonia': {
        'name': 'North Macedonia',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'NATO member, non-nuclear',
    },
    'Greenland': {
        'name': 'Greenland',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.6,
        'description': 'Danish territory, NATO member',
    },
    'Argentine Antarctica': {
        'name': 'Argentina Territory',
        'faction': 'NEUTRAL',
        'alliance': 'none',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.3,
        'description': 'Argentine Antarctic Territory (claimed by Argentina)',
    },
    'Chilean Antarctic Territory': {
        'name': 'Chile Territory',
        'faction': 'NEUTRAL',
        'alliance': 'none',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.3,
        'description': 'Chilean Antarctic Territory (claimed by Chile)',
    },
    'British Antarctic Territory': {
        'name': 'UK Territory',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.4,
        'description': 'British Antarctic Territory (claimed by UK)',
    },
    'Queen Maud Land': {
        'name': 'Norway Territory',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.4,
        'description': 'Queen Maud Land (claimed by Norway)',
    },
    'Australian Antarctic Territory': {
        'name': 'Australia Territory',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.4,
        'description': 'Australian Antarctic Territory (claimed by Australia)',
    },
    'Adélie Land': {
        'name': 'France Territory',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.4,
        'description': 'Adélie Land (claimed by France)',
    },
    'Ross Dependency': {
        'name': 'New Zealand Territory',
        'faction': 'NATO',
        'alliance': 'NATO',
        'nuclear_weapons': 0,
        'nuclear_status': 'none',
        'morale': 0.4,
        'description': 'Ross Dependency (claimed by New Zealand)',
    },
}
