import json

def get_unique_country_code(country_name, existing_codes):
    """Generate unique country code"""
    # Common country code mappings
    code_mapping = {
        'united states of america': 'US',
        'russian federation': 'RU',
        'china': 'CN',
        'united kingdom': 'GB',
        'france': 'FR',
        'germany': 'DE',
        'italy': 'IT',
        'japan': 'JP',
        'india': 'IN',
        'brazil': 'BR',
        'canada': 'CA',
        'australia': 'AU',
        'south korea': 'KR',
        'iran': 'IR',
        'turkey': 'TR',
        'saudi arabia': 'SA',
        'indonesia': 'ID',
        'malaysia': 'MY',
        'chile': 'CL',
        'bolivia': 'BO',
        'peru': 'PE',
        'argentina': 'AR',
        'cyprus': 'CY',
        'netherlands': 'NL',
        'belgium': 'BE',
        'norway': 'NO',
        'denmark': 'DK',
        'sweden': 'SE',
        'finland': 'FI',
        'poland': 'PL',
        'czech republic': 'CZ',
        'slovakia': 'SK',
        'hungary': 'HU',
        'romania': 'RO',
        'bulgaria': 'BG',
        'greece': 'GR',
        'portugal': 'PT',
        'spain': 'ES',
        'ireland': 'IE',
        'iceland': 'IS',
        'luxembourg': 'LU',
        'estonia': 'EE',
        'latvia': 'LV',
        'lithuania': 'LT',
        'slovenia': 'SI',
        'croatia': 'HR',
        'montenegro': 'ME',
        'albania': 'AL',
        'north macedonia': 'MK',
        'kosovo': 'XK',
        'bosnia and herzegovina': 'BA',
        'serbia': 'RS',
        'ukraine': 'UA',
        'moldova': 'MD',
        'georgia': 'GE',
        'armenia': 'AM',
        'azerbaijan': 'AZ',
        'north korea': 'KP',
        'cuba': 'CU',
        'venezuela': 'VE',
        'nicaragua': 'NI',
        'belarus': 'BY',
        'kazakhstan': 'KZ',
        'kyrgyzstan': 'KG',
        'tajikistan': 'TJ',
        'uzbekistan': 'UZ',
        'turkmenistan': 'TM',
        'syria': 'SY',
        'iraq': 'IQ',
        'yemen': 'YE',
        'libya': 'LY',
        'sudan': 'SD',
        'south sudan': 'SS',
        'central african republic': 'CF',
        'mali': 'ML',
        'burkina faso': 'BF',
        'niger': 'NE',
        'chad': 'TD',
        'congo': 'CG',
        'angola': 'AO',
        'zimbabwe': 'ZW',
        'madagascar': 'MG',
        'comoros': 'KM',
        'seychelles': 'SC',
        'mauritius': 'MU',
        'new zealand': 'NZ',
        'mexico': 'MX',
        'colombia': 'CO',
        'ecuador': 'EC',
        'guyana': 'GY',
        'suriname': 'SR',
        'paraguay': 'PY',
        'uruguay': 'UY',
        'fiji': 'FJ',
        'papua new guinea': 'PG',
        'solomon islands': 'SB',
        'vanuatu': 'VU',
        'new caledonia': 'NC',
        'french polynesia': 'PF',
        'samoa': 'WS',
        'tonga': 'TO',
        'tuvalu': 'TV',
        'kiribati': 'KI',
        'marshall islands': 'MH',
        'micronesia': 'FM',
        'palau': 'PW',
        'nauru': 'NR',
        'bangladesh': 'BD',
        'pakistan': 'PK',
        'afghanistan': 'AF',
        'nepal': 'NP',
        'bhutan': 'BT',
        'sri lanka': 'LK',
        'maldives': 'MV',
        'myanmar': 'MM',
        'thailand': 'TH',
        'laos': 'LA',
        'cambodia': 'KH',
        'vietnam': 'VN',
        'philippines': 'PH',
        'taiwan': 'TW',
        'mongolia': 'MN',
        'kyrgyzstan': 'KG',
        'tajikistan': 'TJ',
        'uzbekistan': 'UZ',
        'turkmenistan': 'TM',
        'azerbaijan': 'AZ',
        'georgia': 'GE',
        'armenia': 'AM',
        'moldova': 'MD',
        'ukraine': 'UA',
        'belarus': 'BY',
        'latvia': 'LV',
        'estonia': 'EE',
        'lithuania': 'LT',
        'poland': 'PL',
        'czech republic': 'CZ',
        'slovakia': 'SK',
        'hungary': 'HU',
        'romania': 'RO',
        'bulgaria': 'BG',
        'greece': 'GR',
        'albania': 'AL',
        'north macedonia': 'MK',
        'kosovo': 'XK',
        'serbia': 'RS',
        'montenegro': 'ME',
        'bosnia and herzegovina': 'BA',
        'croatia': 'HR',
        'slovenia': 'SI',
        'austria': 'AT',
        'switzerland': 'CH',
        'liechtenstein': 'LI',
        'monaco': 'MC',
        'andorra': 'AD',
        'san marino': 'SM',
        'vatican city': 'VA',
        'malta': 'MT',
        'morocco': 'MA',
        'algeria': 'DZ',
        'tunisia': 'TN',
        'egypt': 'EG',
        'libya': 'LY',
        'sudan': 'SD',
        'south sudan': 'SS',
        'ethiopia': 'ET',
        'eritrea': 'ER',
        'djibouti': 'DJ',
        'somalia': 'SO',
        'kenya': 'KE',
        'uganda': 'UG',
        'tanzania': 'TZ',
        'rwanda': 'RW',
        'burundi': 'BI',
        'democratic republic of the congo': 'CD',
        'republic of the congo': 'CG',
        'gabon': 'GA',
        'equatorial guinea': 'GQ',
        'sao tome and principe': 'ST',
        'cameroon': 'CM',
        'nigeria': 'NG',
        'niger': 'NE',
        'chad': 'TD',
        'central african republic': 'CF',
        'south sudan': 'SS',
        'ethiopia': 'ET',
        'kenya': 'KE',
        'somalia': 'SO',
        'djibouti': 'DJ',
        'eritrea': 'ER',
        'sudan': 'SD',
        'egypt': 'EG',
        'libya': 'LY',
        'tunisia': 'TN',
        'algeria': 'DZ',
        'morocco': 'MA',
        'western sahara': 'EH',
        'mauritania': 'MR',
        'senegal': 'SN',
        'gambia': 'GM',
        'guinea-bissau': 'GW',
        'guinea': 'GN',
        'sierra leone': 'SL',
        'liberia': 'LR',
        'ivory coast': 'CI',
        'ghana': 'GH',
        'togo': 'TG',
        'benin': 'BJ',
        'nigeria': 'NG',
        'cameroon': 'CM',
        'equatorial guinea': 'GQ',
        'gabon': 'GA',
        'republic of the congo': 'CG',
        'democratic republic of the congo': 'CD',
        'angola': 'AO',
        'namibia': 'NA',
        'botswana': 'BW',
        'zimbabwe': 'ZW',
        'mozambique': 'MZ',
        'zambia': 'ZM',
        'malawi': 'MW',
        'tanzania': 'TZ',
        'kenya': 'KE',
        'somalia': 'SO',
        'ethiopia': 'ET',
        'eritrea': 'ER',
        'djibouti': 'DJ',
        'sudan': 'SD',
        'south sudan': 'SS',
        'central african republic': 'CF',
        'chad': 'TD',
        'niger': 'NE',
        'mali': 'ML',
        'burkina faso': 'BF',
        'senegal': 'SN',
        'mauritania': 'MR',
        'morocco': 'MA',
        'algeria': 'DZ',
        'tunisia': 'TN',
        'libya': 'LY',
        'egypt': 'EG',
        'israel': 'IL',
        'lebanon': 'LB',
        'syria': 'SY',
        'jordan': 'JO',
        'iraq': 'IQ',
        'kuwait': 'KW',
        'saudi arabia': 'SA',
        'yemen': 'YE',
        'oman': 'OM',
        'united arab emirates': 'AE',
        'qatar': 'QA',
        'bahrain': 'BH',
        'iran': 'IR',
        'afghanistan': 'AF',
        'pakistan': 'PK',
        'india': 'IN',
        'nepal': 'NP',
        'bhutan': 'BT',
        'bangladesh': 'BD',
        'myanmar': 'MM',
        'thailand': 'TH',
        'laos': 'LA',
        'cambodia': 'KH',
        'vietnam': 'VN',
        'malaysia': 'MY',
        'singapore': 'SG',
        'brunei': 'BN',
        'indonesia': 'ID',
        'philippines': 'PH',
        'taiwan': 'TW',
        'japan': 'JP',
        'south korea': 'KR',
        'north korea': 'KP',
        'china': 'CN',
        'mongolia': 'MN',
        'kazakhstan': 'KZ',
        'kyrgyzstan': 'KG',
        'tajikistan': 'TJ',
        'uzbekistan': 'UZ',
        'turkmenistan': 'TM',
        'azerbaijan': 'AZ',
        'georgia': 'GE',
        'armenia': 'AM',
        'turkey': 'TR',
        'cyprus': 'CY',
        'greece': 'GR',
        'albania': 'AL',
        'north macedonia': 'MK',
        'kosovo': 'XK',
        'serbia': 'RS',
        'montenegro': 'ME',
        'bosnia and herzegovina': 'BA',
        'croatia': 'HR',
        'slovenia': 'SI',
        'austria': 'AT',
        'switzerland': 'CH',
        'liechtenstein': 'LI',
        'italy': 'IT',
        'san marino': 'SM',
        'vatican city': 'VA',
        'malta': 'MT',
        'spain': 'ES',
        'portugal': 'PT',
        'andorra': 'AD',
        'france': 'FR',
        'monaco': 'MC',
        'belgium': 'BE',
        'netherlands': 'NL',
        'luxembourg': 'LU',
        'germany': 'DE',
        'denmark': 'DK',
        'norway': 'NO',
        'sweden': 'SE',
        'finland': 'FI',
        'iceland': 'IS',
        'united kingdom': 'GB',
        'ireland': 'IE',
        'poland': 'PL',
        'czech republic': 'CZ',
        'slovakia': 'SK',
        'hungary': 'HU',
        'romania': 'RO',
        'bulgaria': 'BG',
        'moldova': 'MD',
        'ukraine': 'UA',
        'belarus': 'BY',
        'latvia': 'LV',
        'estonia': 'EE',
        'lithuania': 'LT',
        'russian federation': 'RU',
        'canada': 'CA',
        'united states of america': 'US',
        'mexico': 'MX',
        'guatemala': 'GT',
        'belize': 'BZ',
        'el salvador': 'SV',
        'honduras': 'HN',
        'nicaragua': 'NI',
        'costa rica': 'CR',
        'panama': 'PA',
        'colombia': 'CO',
        'venezuela': 'VE',
        'guyana': 'GY',
        'suriname': 'SR',
        'french guiana': 'GF',
        'brazil': 'BR',
        'ecuador': 'EC',
        'peru': 'PE',
        'bolivia': 'BO',
        'paraguay': 'PY',
        'chile': 'CL',
        'argentina': 'AR',
        'uruguay': 'UY',
        'australia': 'AU',
        'new zealand': 'NZ',
        'papua new guinea': 'PG',
        'fiji': 'FJ',
        'solomon islands': 'SB',
        'vanuatu': 'VU',
        'new caledonia': 'NC',
        'french polynesia': 'PF',
        'samoa': 'WS',
        'tonga': 'TO',
        'tuvalu': 'TV',
        'kiribati': 'KI',
        'marshall islands': 'MH',
        'micronesia': 'FM',
        'palau': 'PW',
        'nauru': 'NR'
    }
    
    country_lower = country_name.lower()
    
    # Check mapping first
    if country_lower in code_mapping:
        code = code_mapping[country_lower]
        if code not in existing_codes:
            return code
    
    # Try first 2 letters
    code = country_name[:2].upper()
    if code not in existing_codes:
        return code
    
    # Try first 3 letters
    code = country_name[:3].upper()
    if code not in existing_codes:
        return code
    
    # Try first 2 letters of each word
    words = country_name.split()
    if len(words) >= 2:
        code = (words[0][:1] + words[1][:1]).upper()
        if code not in existing_codes:
            return code
    
    # Generate unique code
    counter = 1
    while True:
        code = f"{country_name[:2].upper()}{counter}"
        if code not in existing_codes:
            return code
        counter += 1

def fix_country_codes():
    """Fix country codes to avoid duplicates"""
    try:
        # Load the all countries data
        with open('all-countries-ultra-quality.json', 'r') as f:
            data = json.load(f)
        
        print("Fixing country codes...")
        
        existing_codes = set()
        fixed_features = []
        
        for feature in data['features']:
            country_name = feature['properties']['name']
            new_code = get_unique_country_code(country_name, existing_codes)
            existing_codes.add(new_code)
            
            # Update the feature
            feature['properties']['id'] = new_code
            fixed_features.append(feature)
        
        # Create fixed GeoJSON
        fixed_data = {
            "type": "FeatureCollection",
            "features": fixed_features
        }
        
        # Save fixed version
        with open('all-countries-fixed-codes.json', 'w') as f:
            json.dump(fixed_data, f, indent=2)
        
        print(f"Fixed country codes for {len(fixed_features)} countries")
        print("Saved to: all-countries-fixed-codes.json")
        
        # Show some examples
        print("\nSample fixed codes:")
        for feature in fixed_features[:10]:
            print(f"  {feature['properties']['id']}: {feature['properties']['name']}")
        
        return fixed_data
        
    except Exception as e:
        print(f"Error: {e}")
        return None

if __name__ == "__main__":
    fix_country_codes() 